### ISSUE TITLE
Demo is not installable

### ISSUE THREAD

**Issue by ijpatricio** [archtechx/airwire-demo#1]
Hi @stancl 

As it is, demo is not installable.

On `composer install` we get this:

![image](https://user-images.githubusercontent.com/26031459/122749052-c9e9f080-d284-11eb-9f41-a1b85559b199.png)

On `composer.lock` there's the value from `composer.json` repository...

![image](https://user-images.githubusercontent.com/26031459/122749266-0b7a9b80-d285-11eb-9eb5-86f3c98cf4b3.png)
 

I removed the repo link, and updated, all good.

Also, composer.json has language level allowing 7.3, that will not work.

Would you like me to fix and PR?

**Comment by stancl** [comment]
Ah yeah, nice catch. I'd definitely appreciate the PR!

**Comment by ijpatricio** [comment]
It's done ;)

Also, tests are failing, do they need a look, or is it overengineering for a playground?

Really looking forward where this is going! I too built a similar system (much simpler) to ease the communication between front and backend, and been happily using! 

Have been postponing adding features to it, and seeing someone with similar mindset is just like a blow of fresh air 🙌
